Rule to overcome pvpython crashes

diff --git a/conv_tests/_JB_exp_sin_unstructured/makefile b/conv_tests/_JB_exp_sin_unstructured/makefile
--- a/conv_tests/_JB_exp_sin_unstructured/makefile
+++ b/conv_tests/_JB_exp_sin_unstructured/makefile
@@ -15,7 +15,7 @@ run-all:
 		pvpython ./run_all.py 2>err; \
 		echo "..Ended"; \
 		if [ -f err ]; then \
-			if ! cat err | tail -n 1 | grep "core dumped"; \
+			if ! cat err | tail -n 2 | grep "Aborting"; \
 			then \
 				cat err; \
 				RUN=0; \
